//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWBuildVersion
    {
        public string Database_Version { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public byte SystemInformationID { get; set; }
        public System.DateTime VersionDate { get; set; }
    }
}
