//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderDetail
    {
        public string CarrierTrackingNumber { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public short OrderQty { get; set; }
        public System.Guid rowguid { get; set; }
        public int SalesOrderDetailID { get; set; }
        public int SalesOrderID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> UnitPriceDiscount { get; set; }
    
        public virtual SalesOrderHeader SalesOrderHeader { get; set; }
        public virtual SpecialOfferProduct SpecialOfferProduct { get; set; }
    }
}
