//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Translation
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPersonQuotaHistory
    {
        public System.DateTime ModifiedDate { get; set; }
        public System.DateTime QuotaDate { get; set; }
        public System.Guid rowguid { get; set; }
        public int SalesPersonID { get; set; }
        public Nullable<decimal> SalesQuota { get; set; }
    
        public virtual SalesPerson SalesPerson { get; set; }
    }
}
